STATE_CONFIG = {
    "tamil-nadu": {
        "name": "Tamil Nadu",
        "code": "S22",
        "eci_code": "S22",
        "total_seats": 234,
        "majority": 118,
        "election_date": "2026-04-23",
        "results_date": "2026-05-04",
        "previous_year": 2021,
        "ls_seats": 39,
        "status": "declared",
    },
    "kerala": {
        "name": "Kerala",
        "code": "S11",
        "eci_code": "S11",
        "total_seats": 140,
        "majority": 71,
        "election_date": "2026-04-23",
        "results_date": "2026-05-04",
        "previous_year": 2021,
        "ls_seats": 20,
        "status": "declared",
    },
    "west-bengal": {
        "name": "West Bengal",
        "code": "S25",
        "eci_code": "S25",
        "total_seats": 294,
        "majority": 148,
        "election_date": "2026-04-23",
        "results_date": "2026-05-04",
        "previous_year": 2021,
        "ls_seats": 42,
        "status": "declared",
    },
    "assam": {
        "name": "Assam",
        "code": "S03",
        "eci_code": "S03",
        "total_seats": 126,
        "majority": 64,
        "election_date": "2026-04-23",
        "results_date": "2026-05-04",
        "previous_year": 2021,
        "ls_seats": 14,
        "status": "declared",
    },
    "puducherry": {
        "name": "Puducherry",
        "code": "U07",
        "eci_code": "U07",
        "total_seats": 30,
        "majority": 16,
        "election_date": "2026-04-09",
        "results_date": "2026-05-04",
        "previous_year": 2021,
        "ls_seats": 1,
        "status": "declared",
    },
}
